FROM alpine:3.19

RUN apk update && \
    apk upgrade --no-cache --purge && \
    apk add --no-cache npm nodejs && \
    rm -vrf /var/cache/apk/* 

WORKDIR /app

COPY ["package.json", "./"]

COPY ./src .
COPY tsconfig.json .
COPY tsconfig.build.json .
COPY nest-cli.json .

RUN npm i -g @nestjs/cli && \
    npm i -g pm2@latest && \
    npm install && \
    npm run build 

EXPOSE 3000

CMD [ "pm2", "start", "dist/main.js", "--name", "auth-service", "--watch",  "--ignore-watch", "node_modules", "--no-daemon"]
